### ISSUE TITLE
how to use ZonalOCRinScript.vb?

### ISSUE THREAD

**Issue by gregcho** [KofaxRPA/KTScripts#2]
Hi,
It is really useful script for me.

but I need more explain how to this code.
could please you share small sample project about ZonalOCRinScript.vb?

**Comment by TungstenTransformation** [comment]
fixed
https://github.com/KofaxTransformation/KTScripts/blob/34764aaeb0bcf2aec586be31df80b31a5f63e730/ZonalOCRinScript.vb#L2

**Comment by TungstenTransformation** [comment]
closing
