### ISSUE TITLE
Text Layout Script has the duplicate functions

### ISSUE THREAD

**Issue by stepfox65** [KofaxRPA/KTScripts#9]
Keen to get this code to work as currently working on some AZL and this code looks fantastic.
There are duplicate funtions in the Text Layout.vb script.

When i remove the duplicate functions i can get the Script locator to work but not when i process
it failing in this section of code with fox exception error.
![image](https://github.com/KofaxTransformation/KTScripts/assets/147169002/8e00ce80-1483-4e1a-ab1d-1d61dd67adc0)
cheer stephen fox

**Comment by TungstenTransformation** [comment]
I think you were using the old version of Pages_Compare.
The new version fills Shifts and returns them.
Shifts(0) contains the horizontal shift, scaling and DPI of page 1.
Shifts(1) contains the vertical shift, scaling and DPI of page 1.
Shifts(2) contains the horizontal shift, scaling and DPI of page 2.
Shifts(3) contains the vertical shift, scaling and DPI of page 3. etc

**Comment by stepfox65** [comment]
thanks...that looks better now. Not sure how i got the old code as was just coping and pasting from the code from the link.
Not sure if this work for me yet as im dealing with a dynamic section of a form that can be replicated from 2 to 5 times. They keywords would be the same. I can find the page i want using regular expression and hoping to modify this code to pass in the page number.

The question is why dont they build this type of funtinality into the AZL, movment of zones as we both know is always the biggest issue.

**Comment by stepfox65** [comment]
this still does not seem right
You can't add confidence there is no method.
![image](https://github.com/KofaxTransformation/KTScripts/assets/147169002/d4e3a5d3-ae3b-4db7-8d4d-109247a1de2e)
should it not be 
pLocator.Alternatives(0).Confience =

**Comment by TungstenTransformation** [comment]
Something similar was added to AZL about 2018, so I considered this script obsolete, and was surprised that it was really needed in Sep 2023, so I cleaned up a lot of things in it over the last few weeks. You’ll notice my documentation tells you how to test OCR registration in AZL. Maybe mine works better because it uses hundreds of words and carefully cleans mismatches.
